[workspace]
resolver = "2"
members = [
    "refinery",
    "refinery_cli",
    "refinery_core",
    "refinery_macros",
    "examples",
]

[workspace.package]
rust-version = "1.85"

[profile.release]
codegen-units = 1
lto = true
